import AppKit
import AVFoundation
import Foundation

enum AgentState: String, Codable { case working, completed, failed, awaitingInput = "awaiting-input", off
    var title: String { switch self { case .working: "Working"; case .completed: "Task completed"; case .failed: "Tool call failed"; case .awaitingInput: "Input required"; case .off: "Off" } }
    var color: NSColor { switch self { case .working: .systemYellow; case .completed: .systemGreen; case .failed: .systemRed; case .awaitingInput: .systemOrange; case .off: .secondaryLabelColor } }
}
struct StatusRecord: Codable { var state: AgentState; var updatedAt: Date; var source: String? }

@MainActor final class AppDelegate: NSObject, NSApplicationDelegate {
    private let sources = ["codex", "copilot", "cursor", "claude"]
    private var items: [String: NSStatusItem] = [:]; private var buttonSources: [ObjectIdentifier: String] = [:]; private var states: [String: AgentState] = [:]; private var pulse = 0.0; private var timer: Timer?
    private var players: [String: AVAudioPlayer] = [:]; private var pings: [String: NSSound] = [:]
    private let directory = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Application Support/AgentStatusLight")
    private func name(_ source: String) -> String { source == "copilot" ? "GitHub Copilot" : source.capitalized }
    private func initial(_ source: String) -> String { switch source { case "codex": "O"; case "copilot": "G"; case "cursor": ">"; case "claude": "A"; default: "?" } }
    private func pref(_ key: String) -> Bool { UserDefaults.standard.object(forKey: key) == nil || UserDefaults.standard.bool(forKey: key) }
    private func read(_ source: String) -> AgentState { let d = JSONDecoder(); d.dateDecodingStrategy = .iso8601; guard let x = try? Data(contentsOf: directory.appendingPathComponent("status.\(source).json")), let r = try? d.decode(StatusRecord.self, from: x) else { return .off }; return r.state == .completed && Date().timeIntervalSince(r.updatedAt) >= 20 ? .off : r.state }
    func applicationDidFinishLaunching(_ n: Notification) { for source in sources { let item = NSStatusBar.system.statusItem(withLength: 28); item.button?.target = self; item.button?.action = #selector(menu(_:)); if let button = item.button { buttonSources[ObjectIdentifier(button)] = source; button.setAccessibilityLabel("Agent Status Light: \(name(source))") }; items[source] = item; states[source] = read(source); render(source) }; timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in Task { @MainActor in self?.refresh() } } }
    private func refresh() { pulse += 0.24; for source in sources { let old = states[source] ?? .off; let new = read(source); if old != new { states[source] = new; if new == .failed && pref("playFailureSound") { failure(source) }; if new == .awaitingInput && pref("playInputSound") { ping(source) } }; if new == .working || old != new { render(source) } } }
    @objc private func menu(_ sender: NSStatusBarButton) { guard let source = buttonSources[ObjectIdentifier(sender)] else { return }; let m = NSMenu(); let h = NSMenuItem(title: "\(name(source)): \(states[source]?.title ?? "Off")", action: nil, keyEquivalent: ""); h.isEnabled = false; m.addItem(h); m.addItem(.separator()); let choose = NSMenuItem(title: "Choose logo…", action: #selector(choose(_:)), keyEquivalent: ""); choose.target = self; choose.representedObject = source; m.addItem(choose); let clear = NSMenuItem(title: "Use initial instead", action: #selector(clear(_:)), keyEquivalent: ""); clear.target = self; clear.representedObject = source; m.addItem(clear); m.addItem(.separator()); let f = NSMenuItem(title: "Play failure sound", action: #selector(toggleFailure), keyEquivalent: ""); f.target = self; f.state = pref("playFailureSound") ? .on : .off; m.addItem(f); let p = NSMenuItem(title: "Play input-request sound", action: #selector(toggleInput), keyEquivalent: ""); p.target = self; p.state = pref("playInputSound") ? .on : .off; m.addItem(p); items[source]?.menu = m; sender.performClick(nil); items[source]?.menu = nil }
    @objc private func choose(_ s: NSMenuItem) { guard let source = s.representedObject as? String else { return }; let p = NSOpenPanel(); p.allowedFileTypes = ["png", "icns", "jpg", "jpeg", "tiff"]; if p.runModal() == .OK, let u = p.url { UserDefaults.standard.set(u.path, forKey: "iconPath.\(source)"); render(source) } }
    @objc private func clear(_ s: NSMenuItem) { if let source = s.representedObject as? String { UserDefaults.standard.removeObject(forKey: "iconPath.\(source)"); render(source) } }
    @objc private func toggleFailure() { UserDefaults.standard.set(!pref("playFailureSound"), forKey: "playFailureSound") }; @objc private func toggleInput() { UserDefaults.standard.set(!pref("playInputSound"), forKey: "playInputSound") }; @objc private func quit() { NSApp.terminate(nil) }
    private func render(_ source: String) { guard let b = items[source]?.button else { return }; let state = states[source] ?? .off; let image = NSImage(size: NSSize(width: 20, height: 18)); image.lockFocus(); let a = state == .working ? 0.45 + (sin(pulse) + 1) * 0.275 : 1.0; if let path = UserDefaults.standard.string(forKey: "iconPath.\(source)"), let logo = NSImage(contentsOfFile: path) { logo.draw(in: NSRect(x: 2, y: 2, width: 14, height: 14), from: .zero, operation: .sourceOver, fraction: a) } else { state.color.withAlphaComponent(a).setFill(); NSBezierPath(ovalIn: NSRect(x: 2, y: 2, width: 14, height: 14)).fill(); (initial(source) as NSString).draw(at: NSPoint(x: 6, y: 3), withAttributes: [.font: NSFont.boldSystemFont(ofSize: 9), .foregroundColor: NSColor.white]) }; image.unlockFocus(); b.image = image; b.toolTip = "\(name(source)): \(state.title)" }
    private func ping(_ source: String) { pings[source] = NSSound(named: NSSound.Name("Ping")); if pings[source]?.play() != true { NSSound.beep() } }
    private func failure(_ source: String) { let rate = 44100, count = Int(Double(rate) * 0.58); var samples = [Int16](repeating: 0, count: count); let notes = [(0.0, 0.24, 494.0), (0.29, 0.25, 370.0)]; for i in samples.indices { let t = Double(i) / Double(rate); var v = 0.0; for (s,l,f) in notes where t >= s && t < s+l { let n=t-s; let e=min(n/0.018,1)*min((s+l-t)/0.075,1); let q=2*Double.pi*f*n; v += e*(sin(q)+0.32*sin(2*q)+0.12*sin(3*q)) }; samples[i]=Int16(max(-1,min(1,v*0.38))*Double(Int16.max)) }; var d=Data(); func put<T:FixedWidthInteger>(_ x:T){var y=x.littleEndian; withUnsafeBytes(of:&y){d.append(contentsOf:$0)}}; let z=UInt32(samples.count*2); d.append("RIFF".data(using:.ascii)!); put(UInt32(36)+z); d.append("WAVEfmt ".data(using:.ascii)!); put(UInt32(16)); put(UInt16(1)); put(UInt16(1)); put(UInt32(rate)); put(UInt32(rate*2)); put(UInt16(2)); put(UInt16(16)); d.append("data".data(using:.ascii)!); put(z); for x in samples {put(x)}; do {players[source]=try AVAudioPlayer(data:d); players[source]?.volume=0.65; players[source]?.play()} catch {NSSound.beep()} }
}
let app = NSApplication.shared; app.setActivationPolicy(.accessory); let delegate = AppDelegate(); app.delegate = delegate; app.run()
